## Deliverable: Functions and Graphics

# Write a function countOdds() that takes an array of numbers as an input and returns the number of odd ones. Make sure to use the name countOdds for your function.

```{r}
countOdds <- function(x){return(sum(x%%2))}
```

```{r}
countOdds(1:9)
```

```{r}
countEven <- function(x){return(sum(x%%2==0))}
```

```{r}
countEven(1:9)
```

```{r}
hypotenuseLength <- function(a,b){return(sqrt(a^2+b^2))}
```

```{r}
hypotenuseLength(3,4)
```

```{r}
lawOfCosines <- function(a,b,theta){return(sqrt(a^2+b^2-2*a*b*cos(theta)))}
```

```{r}
lawOfCosines(13,84,pi/2)
```

```{r}
thetafromLengths <- function(a,b,c){return(acos((c^2-a^2-b^2)/((-1)*2*a*b)))}
```

```{r}
thetafromLengths(3,4,5)
```

```{r}
thetaFromLengthsTest <- function(a,b,theta){return(thetafromLengths(a,b,lawOfCosines(a,b,theta))-theta)}
```

```{r}
thetaFromLengthsTest(3,4,pi/3)
```

```{r}
canvas <- function(a,b){return(plot(a:b,type="n",xlim=c(1,100),ylim=c(1,100),xlab="",ylab=""))}
```

```{r}
canvas(2,3)
```

```{r}
drawCircle <- function(x,y,r,z){return(polygon(x+r*cos(seq(0,2*pi,length=1000),y+r*sin(seq(0,2*pi,length=1000),col=z,border=NULL))}
```

```{r}
drawCircle(50,50,15,"maroon")
```

```{r}
drawCircle <- function(x,y,r,...){return(polygon(x+r*cos(seq(0,2*pi,length=1000)),y+r*sin(seq(0,2*pi,length=1000)),...))}
```

```{r}
drawCircle(23,23,10,col="maroon")
```

```{r}
drawCircle(20,20,9,col="NA",border="blue",lwd=4)
```