October 3, 2013

```{r}
myfactorial<-function(n){
  res<-1
  for(k in 1:n){
  res<-res*k
  }
  return(res)
  }
```

```{r}
myfactorial(5)
```


```{r}
mysum<-function(n){
  res<-0
  for(k in 1:n){
    res<-res+k
    }
  return(res)
  }
```

```{r}
mysum(5)
mysum(10)
```

```{r}
words <- readLines(url("http://dtkaplan.github.io/ScientificComputing/Syllabus/Daily/Day-07/word_list_moby_crossword-flat/word_list_moby_crossword.flat.txt"))
```
# length words
```{r}
findscrabble<-function(letters){
  for(k in 1:3){
  words<-words[grep(letters[1],words)]
  words<-words[grep(letters[2],words)]
  words<-words[grep(letters[3],words)]}
  return(words)
  }
```

```{r}
findscrabble<-function(letters){
  for(k in 1:length(letters)){
    words<-words[grep(letters[k],words)]
  if(length(words)<10)break
  }
  return(words)
  }
  
```{r}
length(findscrabble(c("b","n","r")))
```
               
```{r}
findscrabble(c("b","r","n","x","a","c","z"))
```

```{r}
fibonacci<-function(n){
  current<-1
  beforeIt<-0
  for(k in 1:n){
  tmp<-current + beforeIt
  beforeIt<-current
  current<-tmp}
  return(current)
  }
```

```{r}
fibonacci(6)
fibonacci(7)
fibonacci(8)
```

```{r}
fibonacci<-function(n){
  if(n<0 | floor(n) !=n) {
    warning("STOP IT NOW")
    return("Helllll no")
}
  sofar=c(0,1)
  for(k in 3:n){
  sofar[k]<-sofar[k-1] + sofar[k-2]
  }
  return(sofar)
  }
```

```{r}
fibonacci(3)
fibonacci(10)
fibonacci(-5)
```

```{r}
primeSieve<-function(n){
guess=rep(TRUE,n)
inds<-1:n
for(k in 2:n){
  if (guess[k] ) {
  guess[(inds%%k)==0 & inds>k]<-FALSE
  }
}
return(which(guess))
}
```

```{r}
primeSieve(100)
```
